# Generated by Django 4.2.29 on 2026-03-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
