# Generated by Django 4.2.29 on 2026-03-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
    ]
