# Generated by Django 4.2.29 on 2026-03-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('ventas', '0003_remove_venta_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('subtotal', models.IntegerField(default=0)),
                ('producto_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productostock')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
