# Generated by Django 4.2.29 on 2026-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detalleventastock'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
