# Generated by Django 4.2.29 on 2026-03-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventastock',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
