# Generated by Django 4.2.29 on 2026-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocampana',
            options={'verbose_name': 'Producto por campaña', 'verbose_name_plural': 'Productos por campaña'},
        ),
        migrations.AddField(
            model_name='productocampana',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
